import type { NextPage } from "next";
import Head from "next/head";
import { gql, useQuery } from "@apollo/client";
import TodoList from "../components/TodoList";
import TodoForm from "../components/TodoForm";
import { Container, Heading, Stack } from "@chakra-ui/react";
import { Todo } from "../graphql/types";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container my="32px">
          <Stack spacing="32px">
            <Heading>Todo List</Heading>
            <TodoForm />
            <TodoList />
          </Stack>
        </Container>
      </main>
    </div>
  );
};

export default Home;
